#!/usr/bin/env python3
"""Generate acids_mel_tables.h from mel_preprocess.build_mel_filterbank."""

import argparse
import sys
from pathlib import Path

import torch

src2 = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(src2))

from data_augmenter.mel_preprocess import build_mel_filterbank  # noqa: E402

DEFAULT_N_FFT = 160
DEFAULT_N_MEL = 80
DEFAULT_FMIN = 20.0
DEFAULT_FMAX = 800.0
DEFAULT_SAMPLE_RATE = 1600


def emit_rfft_tables(out_path: Path, n_fft: int) -> None:
    """Export float32 RFFT basis matrices derived from torch.fft.rfft."""
    n_bins = n_fft // 2 + 1
    real = torch.zeros(n_bins, n_fft, dtype=torch.float32)
    imag = torch.zeros(n_bins, n_fft, dtype=torch.float32)
    for t in range(n_fft):
        e = torch.zeros(n_fft, dtype=torch.float32)
        e[t] = 1.0
        X = torch.fft.rfft(e, n=n_fft)
        real[:, t] = X.real
        imag[:, t] = X.imag

    lines = [
        "/* Auto-generated RFFT basis (torch.fft.rfft) — do not edit. */",
        f"#define ACIDS_RFFT_MATRIX_BINS {n_bins}",
        f"#define ACIDS_RFFT_MATRIX_LEN {n_fft}",
        "",
        f"static const float ACIDS_RFFT_REAL[{n_bins}][{n_fft}] = {{",
    ]
    for k in range(n_bins):
        row = ", ".join(_fmt_float(real[k, t].item()) for t in range(n_fft))
        lines.append(f"    {{ {row} }}{',' if k + 1 < n_bins else ''}")
    lines.append("};")
    lines.append("")
    lines.append(f"static const float ACIDS_RFFT_IMAG[{n_bins}][{n_fft}] = {{")
    for k in range(n_bins):
        row = ", ".join(_fmt_float(imag[k, t].item()) for t in range(n_fft))
        lines.append(f"    {{ {row} }}{',' if k + 1 < n_bins else ''}")
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _fmt_float(v: float) -> str:
    if v == 0.0:
        return "0.0f"
    if v == 1.0:
        return "1.0f"
    if v == -1.0:
        return "-1.0f"
    return f"{v:.9g}f"


def emit_header(fb, out_path: Path, n_fft: int, n_mel: int) -> None:
    n_freqs = n_fft // 2 + 1
    lines = [
        "/* Auto-generated by export_mel_tables.py — do not edit. */",
        "#ifndef ACIDS_MEL_TABLES_H",
        "#define ACIDS_MEL_TABLES_H",
        "",
        f"#define ACIDS_MEL_NUM_FILTERS {n_mel}",
        f"#define ACIDS_MEL_NUM_FFT_BINS {n_freqs}",
        "",
        f"static const float ACIDS_MEL_FILTERBANK[{n_mel}][{n_freqs}] = {{",
    ]
    fb_np = fb.cpu().numpy()
    for m in range(n_mel):
        row = ", ".join(_fmt_float(float(fb_np[m, k])) for k in range(n_freqs))
        lines.append(f"    {{ {row} }}{',' if m + 1 < n_mel else ''}")
    lines.extend(["};", "", "#endif /* ACIDS_MEL_TABLES_H */", ""])
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Export mel filterbank to C header")
    parser.add_argument("--n_fft", type=int, default=DEFAULT_N_FFT)
    parser.add_argument("--n_mel", type=int, default=DEFAULT_N_MEL)
    parser.add_argument("--fmin", type=float, default=DEFAULT_FMIN)
    parser.add_argument("--fmax", type=float, default=DEFAULT_FMAX)
    parser.add_argument("--sample_rate", type=int, default=DEFAULT_SAMPLE_RATE)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent / "acids_mel_tables.h",
    )
    parser.add_argument(
        "--rfft_output",
        type=Path,
        default=Path(__file__).parent / "acids_rfft_tables.h",
    )
    args = parser.parse_args()

    fb = build_mel_filterbank(
        args.n_fft, args.n_mel, args.fmin, args.fmax, args.sample_rate
    )
    emit_header(fb, args.output, args.n_fft, args.n_mel)
    emit_rfft_tables(args.rfft_output, args.n_fft)
    print(f"Wrote {args.output} ({args.n_mel}x{args.n_fft // 2 + 1})")
    print(f"Wrote {args.rfft_output} (rfft basis {args.n_fft // 2 + 1}x{args.n_fft})")


if __name__ == "__main__":
    main()
